"""add all models for smartedu platform

Revision ID: 523fc0e280aa
Revises: 3e2bd84a6c57
Create Date: 2026-01-17 22:38:56.200727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523fc0e280aa'
down_revision: Union[str, Sequence[str], None] = '3e2bd84a6c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
